name: build-and-publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Tooolchain Installation
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Wasm-pack Installation
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Wasm-pack build
        run: wasm-pack build --target web
      - name: Create github pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pkg
  deploy:
    needs: build
    permissions:
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs
